// Code generated by rclgo-gen. DO NOT EDIT.

package msgs

import (
	_ "github.com/vaffeine/rclgo-parameter-server/internal/msgs/builtin_interfaces/msg" //
	_ "github.com/vaffeine/rclgo-parameter-server/internal/msgs/rcl_interfaces/msg" //
	_ "github.com/vaffeine/rclgo-parameter-server/internal/msgs/rcl_interfaces/srv" //
)
